language: C

install:
  # Prerequisites
  - "sudo apt-get install autopoint libreadline-dev wget texinfo"

# run the tests
script: autoreconf -i && ./configure && make update && (cd doc && make stamp-vti) && make && TRAVIS=1 make check
